#import = [
  # uncomment the flavour you want below:
  #"/home/ac/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
#   "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
#]

[font]
size = 16.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[window]
opacity = 1
blur = true

[env]
TERM = "xterm-256color"
